# Generated by Django 3.2.12 on 2024-04-27 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240427_0233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
