# Generated by Django 3.2.12 on 2024-04-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20240427_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sender_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
