# Generated by Django 3.2.12 on 2024-04-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_note_trial_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='trial_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
