# Generated by Django 3.2.12 on 2024-04-30 21:12

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_note_trial_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='caseNumber',
            field=models.CharField(default='123', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_casenumber', message='Case number must contain only numeric characters.', regex='^[0-9]*$')]),
        ),
        migrations.AddField(
            model_name='note',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
