# Generated by Django 3.2.12 on 2024-04-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20240430_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='trial_date',
        ),
    ]
