# Generated by Django 3.2.12 on 2024-05-03 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20240503_0231'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='note',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
