# Generated by Django 3.2.12 on 2024-05-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20240503_0235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='note',
            name='start_time',
        ),
        migrations.AddField(
            model_name='note',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
