# Generated by Django 3.2.12 on 2024-05-03 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20240503_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='end_date',
        ),
    ]
