# Generated by Django 3.2.12 on 2024-05-03 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_remove_note_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
