# Generated by Django 3.2.12 on 2024-05-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20240503_0309'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='confirmed_attendance',
            field=models.BooleanField(default=False),
        ),
    ]
