# Generated by Django 3.2.12 on 2024-05-03 11:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_note_confirmed_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='caseNumber',
        ),
        migrations.AddField(
            model_name='note',
            name='centralComplaint',
            field=models.CharField(default='123', max_length=200, validators=[django.core.validators.RegexValidator(code='invalid_centralComplaint', message='Central Complaint must contain only numeric characters.', regex='^[0-9]*$')]),
        ),
    ]
